spring:
  datasource:
    username: root
    password: Harsh@123
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
       defaultZone: http://service-registry:8761/eureka/

