spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true
server:
  port: 8082
  servlet:
    context-path: /order
feign:
  hystrix:
    enabled: true

