spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true
server:
  port: 8081
  servlet:
    context-path: /product

